name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ warp/develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: | 
          ./scripts/install_deps.sh
          
      - name: Install evmone (linux)
        run: |
          mkdir -p deps
          cd deps
          wget https://github.com/ethereum/evmone/releases/download/v0.8.0/evmone-0.8.0-linux-x86_64.tar.gz
          tar -xvzf evmone-0.8.0-linux-x86_64.tar.gz
          cd ..
        if: matrix.config.os == 'ubuntu-latest'
        
      - name: Install evmone (macos)
        run: |
          mkdir -p deps
          cd deps
          wget https://github.com/ethereum/evmone/releases/download/v0.8.0/evmone-0.8.0-darwin-x86_64.tar.gz
          tar -xvzf evmone-0.8.0-darwin-x86_64.tar.gz
          cd ..
        if: matrix.config.os == 'macos-10.15'

      - name: Gen Cache Id
        run: |
          echo "::set-output name=timestamp::$(date '+%s')"
        id: cache-id
        
      - name: Cache build
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: build
          key: ${{ matrix.config.os }}-build-${{ steps.cache-id.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.conig.os }}-build-
            
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. && make
        
      - name: Test
        run: |
          TERM=dumb SMT_FLAGS=--no-smt ./scripts/tests.sh
