name: Build and test

on:
  workflow_dispatch:
  push:
    branches: [ warp/develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-10.15


    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          ./scripts/install_deps.sh

      - name: Gen Cache Id
        run: |
          echo "::set-output name=timestamp::$(date '+%s')"
        id: cache-id

      - name: Cache build
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: build
          key: ${{ matrix.config.os }}-build-${{ steps.cache-id.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.conig.os }}-build-

      - name: Build
        run: |
          mkdir build
          cd build
          TERM=dumb cmake .. && make

      - name: Upload the solc artifact
        uses: actions/upload-artifact@v2
        with:
            name: solc
            path: build/solc/solc
